//<auto-generated>
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Evently.Module.User.InfraStructure.Database.Migrations
{
    /// <inheritdoc />
    public partial class UpdatingSnackCase : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropPrimaryKey(
                name: "PK_Users",
                schema: "Client",
                table: "Users");

            migrationBuilder.DropPrimaryKey(
                name: "PK_outbox_messages",
                schema: "Client",
                table: "outbox_messages");

            migrationBuilder.DropPrimaryKey(
                name: "PK_outbox_message_consumers",
                schema: "Client",
                table: "outbox_message_consumers");

            migrationBuilder.RenameTable(
                name: "Users",
                schema: "Client",
                newName: "users",
                newSchema: "Client");

            migrationBuilder.RenameColumn(
                name: "Email",
                schema: "Client",
                table: "users",
                newName: "email");

            migrationBuilder.RenameColumn(
                name: "UserName",
                schema: "Client",
                table: "users",
                newName: "user_name");

            migrationBuilder.RenameColumn(
                name: "IdentityId",
                schema: "Client",
                table: "users",
                newName: "identity_id");

            migrationBuilder.RenameColumn(
                name: "GuidId",
                schema: "Client",
                table: "users",
                newName: "guid_id");

            migrationBuilder.RenameColumn(
                name: "CreatedateTime",
                schema: "Client",
                table: "users",
                newName: "createdate_time");

            migrationBuilder.RenameColumn(
                name: "ClientGuid",
                schema: "Client",
                table: "users",
                newName: "client_guid");

            migrationBuilder.RenameIndex(
                name: "IX_Users_Email",
                schema: "Client",
                table: "users",
                newName: "ix_users_email");

            migrationBuilder.RenameIndex(
                name: "IX_Users_IdentityId",
                schema: "Client",
                table: "users",
                newName: "ix_users_identity_id");

            migrationBuilder.RenameColumn(
                name: "Type",
                schema: "Client",
                table: "outbox_messages",
                newName: "type");

            migrationBuilder.RenameColumn(
                name: "Error",
                schema: "Client",
                table: "outbox_messages",
                newName: "error");

            migrationBuilder.RenameColumn(
                name: "Content",
                schema: "Client",
                table: "outbox_messages",
                newName: "content");

            migrationBuilder.RenameColumn(
                name: "Id",
                schema: "Client",
                table: "outbox_messages",
                newName: "id");

            migrationBuilder.RenameColumn(
                name: "ProcessedOnUtc",
                schema: "Client",
                table: "outbox_messages",
                newName: "processed_on_utc");

            migrationBuilder.RenameColumn(
                name: "OccurredOnUtc",
                schema: "Client",
                table: "outbox_messages",
                newName: "occurred_on_utc");

            migrationBuilder.RenameColumn(
                name: "Name",
                schema: "Client",
                table: "outbox_message_consumers",
                newName: "name");

            migrationBuilder.RenameColumn(
                name: "OutboxMessageId",
                schema: "Client",
                table: "outbox_message_consumers",
                newName: "outbox_message_id");

            migrationBuilder.AddPrimaryKey(
                name: "pk_users",
                schema: "Client",
                table: "users",
                column: "client_guid");

            migrationBuilder.AddPrimaryKey(
                name: "pk_outbox_messages",
                schema: "Client",
                table: "outbox_messages",
                column: "id");

            migrationBuilder.AddPrimaryKey(
                name: "pk_outbox_message_consumers",
                schema: "Client",
                table: "outbox_message_consumers",
                columns: new[] { "outbox_message_id", "name" });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropPrimaryKey(
                name: "pk_users",
                schema: "Client",
                table: "users");

            migrationBuilder.DropPrimaryKey(
                name: "pk_outbox_messages",
                schema: "Client",
                table: "outbox_messages");

            migrationBuilder.DropPrimaryKey(
                name: "pk_outbox_message_consumers",
                schema: "Client",
                table: "outbox_message_consumers");

            migrationBuilder.RenameTable(
                name: "users",
                schema: "Client",
                newName: "Users",
                newSchema: "Client");

            migrationBuilder.RenameColumn(
                name: "email",
                schema: "Client",
                table: "Users",
                newName: "Email");

            migrationBuilder.RenameColumn(
                name: "user_name",
                schema: "Client",
                table: "Users",
                newName: "UserName");

            migrationBuilder.RenameColumn(
                name: "identity_id",
                schema: "Client",
                table: "Users",
                newName: "IdentityId");

            migrationBuilder.RenameColumn(
                name: "guid_id",
                schema: "Client",
                table: "Users",
                newName: "GuidId");

            migrationBuilder.RenameColumn(
                name: "createdate_time",
                schema: "Client",
                table: "Users",
                newName: "CreatedateTime");

            migrationBuilder.RenameColumn(
                name: "client_guid",
                schema: "Client",
                table: "Users",
                newName: "ClientGuid");

            migrationBuilder.RenameIndex(
                name: "ix_users_email",
                schema: "Client",
                table: "Users",
                newName: "IX_Users_Email");

            migrationBuilder.RenameIndex(
                name: "ix_users_identity_id",
                schema: "Client",
                table: "Users",
                newName: "IX_Users_IdentityId");

            migrationBuilder.RenameColumn(
                name: "type",
                schema: "Client",
                table: "outbox_messages",
                newName: "Type");

            migrationBuilder.RenameColumn(
                name: "error",
                schema: "Client",
                table: "outbox_messages",
                newName: "Error");

            migrationBuilder.RenameColumn(
                name: "content",
                schema: "Client",
                table: "outbox_messages",
                newName: "Content");

            migrationBuilder.RenameColumn(
                name: "id",
                schema: "Client",
                table: "outbox_messages",
                newName: "Id");

            migrationBuilder.RenameColumn(
                name: "processed_on_utc",
                schema: "Client",
                table: "outbox_messages",
                newName: "ProcessedOnUtc");

            migrationBuilder.RenameColumn(
                name: "occurred_on_utc",
                schema: "Client",
                table: "outbox_messages",
                newName: "OccurredOnUtc");

            migrationBuilder.RenameColumn(
                name: "name",
                schema: "Client",
                table: "outbox_message_consumers",
                newName: "Name");

            migrationBuilder.RenameColumn(
                name: "outbox_message_id",
                schema: "Client",
                table: "outbox_message_consumers",
                newName: "OutboxMessageId");

            migrationBuilder.AddPrimaryKey(
                name: "PK_Users",
                schema: "Client",
                table: "Users",
                column: "ClientGuid");

            migrationBuilder.AddPrimaryKey(
                name: "PK_outbox_messages",
                schema: "Client",
                table: "outbox_messages",
                column: "Id");

            migrationBuilder.AddPrimaryKey(
                name: "PK_outbox_message_consumers",
                schema: "Client",
                table: "outbox_message_consumers",
                columns: new[] { "OutboxMessageId", "Name" });
        }
    }
}
