//<auto-generated>
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Evently.Module.User.InfraStructure.Database.Migrations
{
    /// <inheritdoc />
    public partial class Initial_Create : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {

        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {

        }
    }
}
